"""State definitions for the LangGraph research workflow."""
from typing import Annotated, Any, TypedDict
from operator import add


class ResearchState(TypedDict):
    """Shared state flowing through the research graph."""

    # Input
    topic: str
    session_id: str
    recipient_email: str

    # Plan-and-Execute: sub-queries generated by the planner
    plan: list[str]

    # Accumulated search results (reducer: add = append to list)
    search_results: Annotated[list[dict[str, Any]], add]

    # Summaries for each batch of results
    summaries: Annotated[list[str], add]

    # Final output
    report: str

    # Flow control
    current_step: str
    error: str
    done: bool
